fix: make error box dismissable
distributeaid/chat-ui pull request #44
Opened 2020-05-06 07:15 UTC by vipin8169

2020-05-06 07:28 UTC, coderbyheart requested changes
This does not make the error box dismissable, instead it hides the error after 5 seconds.

This is a distinctly different solution, and has usability issues. If the user does not pay attention, or is on another screen while the error happens, they might not even see the error message.

This makes it also very hard for users to share error messages (because they will immediately disappear).

I have updated the issue description to reflect that user interaction should be needed to dismiss the error box.

2020-05-06 07:45 UTC, vipin8169 commented
How would you like to get it dismissed? do you want a cross button to dismiss it? what user action should make it disappear?

2020-05-06 09:22 UTC, coderbyheart commented
A `X` icon is a typical UI element which allows to dismiss error messages, so yes, that could be a solution.

2020-05-07 09:05 UTC, coderbyheart requested changes
![image](https://user-images.githubusercontent.com/188915/81275872-8f0e0480-9052-11ea-8c8e-b9ca42e68565.png)

The positioning of the `X` button does not handle error message which are longer.

2020-05-07 09:08 UTC, vipin8169 commented
I am not sure what you mean. I request you to please elaborate and provide more information, and also a way to reproduce the problem.

2020-05-07 09:09 UTC, vipin8169 commented
Should I rather place the x button at the bottom right corner of this red message box?

2020-05-07 09:16 UTC, coderbyheart commented
> I am not sure what you mean. I request you to please elaborate and provide more information, and also a way to reproduce the problem.

Add some text to the error message to make it longer, then you will see what is shown in the screenshot above.

> Should I rather place the x button at the bottom right corner of this red message box?

No, like in the development warning, the button should be in the top right corner.

![image](https://user-images.githubusercontent.com/188915/81277030-20ca4180-9054-11ea-8297-a687df71e87b.png)

2020-05-08 20:51 UTC, vipin8169 commented
Can you please take a look at the new changes and merge this pr if everything is as expected.

2020-05-09 10:03 UTC, coderbyheart commented
Yes, I first want to set up a way to preview PRs (#46), otherwise I always have to check them out locally.

2020-05-09 10:17 UTC, vipin8169 commented
ok. Let me know if you would want to me to look at anything else in the meantime.

2020-05-09 13:01 UTC, coderbyheart requested changes
![image](https://user-images.githubusercontent.com/188915/81474454-dd173980-9205-11ea-9fc7-249d6af11fde.png)

The close buttons in the red and the yellow box do not align.

2020-05-10 09:11 UTC, vipin8169 commented
Updated the code to align the two.

2020-05-10 11:05 UTC, coderbyheart requested changes
![image](https://user-images.githubusercontent.com/188915/81497451-dd274000-92be-11ea-82f3-e731b91cf0d5.png)

Now the text does not align with the one in the yellow box.

2020-05-11 04:48 UTC, vipin8169 commented
fixed

2020-05-11 07:08 UTC, coderbyheart commented
I think you forgot to push, the last commit is 83926e19e7d5fe78f27ff8f4cdc9a6143a8533aa which is from 22 hours ago.

2020-05-11 08:51 UTC, vipin8169 commented
Sorry, my bad. pushed it now

2020-05-11 16:53 UTC, coderbyheart requested changes
![image](https://user-images.githubusercontent.com/188915/81588066-3a52ec80-93b8-11ea-912c-5fda1b40914b.png)

Not that the vertical space between the button and the top of the box is different to the yellow box.

![image](https://user-images.githubusercontent.com/188915/81588084-463eae80-93b8-11ea-90bc-41c3722b6309.png)

Please pay attention to these differences.

You could solve this by create an `DismissableBox` component which has the same styles for positioning text and close buttons and re-use this in both cases.

2020-05-12 04:33 UTC, vipin8169 commented
fixed

2020-05-12 07:41 UTC, coderbyheart requested changes
![image](https://user-images.githubusercontent.com/188915/81652883-b0953480-9434-11ea-8753-60204378be6a.png)

2020-05-13 01:44 UTC, vipin8169 commented
fixed.

2020-05-13 08:05 UTC, coderbyheart approved these changes
Ok, it now looks the same. I think this can be further improved in another PR and re-use the [Notice](https://github.com/distributeaid/chat-ui/blob/saga/src/Chat/components/Notice.tsx) component.

2020-05-13 08:05 UTC, coderbyheart commented on src/Chat/components/Error.tsx
> +	else
```suggestion
```
This is not neccessary. The return in the previous line will end the function execution.

2020-05-13 22:56 UTC, vipin8169 commented
Can we merge this one?

2020-05-14 07:17 UTC, coderbyheart commented
Yes, it's approved!

2020-05-14 07:30 UTC, vipin8169 commented
but it has not been merged yet :/

2020-05-14 07:38 UTC, coderbyheart commented
Can't you do that?

2020-05-14 07:53 UTC, vipin8169 commented
I am not authorized to merge this pull request.

2020-05-14 07:59 UTC, merged